name: CI

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  CI:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21.6.2
          
